### ISSUE TITLE
Filter Reference Example?

### ISSUE THREAD

**Issue by ghost** [obenland/wp-search-suggest#1]
Hello,

Awesome plugin! I am just wondering how to use the filters you have provided. 

Would you be able to show me an example? Such as only searching for Posts and not Pages as well?

**Comment by obenland** [comment]
I'm sorry this is a development issue tracker, not a support forum.
Please post development questions that are not bugs over at the WordPress Support Forum:
http://wordpress.org/support/plugin/wp-search-suggest

Thanks!

**Comment by trewknowledge** [comment]
My apologies.
