### ISSUE TITLE
Search suggest doesn't show custom fields

### ISSUE THREAD

**Issue by filiprund** [obenland/wp-search-suggest#3]
Hi, and thanks for a great plugin! I really like it! I have one issue though;
It seems like the plugin does not find content that are displayed using custom fields, in my case Advanced Custom Fields. For example, on a page that uses the `the_content();` function to display the string "Lorem ipsum", the page shows up as a suggestion when I search for "Lorem". But another page that uses a custom field to display "Lorem ipsum" does not show up. Is that something that can be easily tweaked?

I'm only asking here because I've had no luck in the [forum](https://wordpress.org/support/plugin/wp-search-suggest/page/1/).

**Comment by obenland** [comment]
It uses `WP_Query` internally, so it works like any other search. If you made your custom fields available to search in general it should also show up in suggestions.
